version: '2'

services:
    web:
        image: s9s/wp-plugin-web:1.0
        container_name: web
        links:
            - mysql
        environment:
            WORDPRESS_DB_PASSWORD: password
            WORDPRESS_DEBUG: 1
        ports:
            - "3000:80"
        volumes:
            - ${HOST_PWD}/dist/${PROJECT_NAME_SLUG}-free.zip:/tmp/${PROJECT_NAME_SLUG}-free.zip
            - ${HOST_PWD}/dist/${PROJECT_NAME_SLUG}-free-debug.zip:/tmp/${PROJECT_NAME_SLUG}-free-debug.zip
            - ${HOST_PWD}/dist/${PROJECT_NAME_SLUG}-premium.zip:/tmp/${PROJECT_NAME_SLUG}-premium.zip
            - ${HOST_PWD}/dist/${PROJECT_NAME_SLUG}-premium-debug.zip:/tmp/${PROJECT_NAME_SLUG}-premium-debug.zip
    mysql:
        image: mysql:5.7
        container_name: db
        environment:
            - MYSQL_ROOT_PASSWORD=password
            - MYSQL_DATABASE=my-wpdb
