version: '2'

services:
  web:
    image: wordpress
    links:
      - mysql
    environment:
      - WORDPRESS_DB_PASSWORD=password
      - WORDPRESS_DEBUG=1
    ports:
      - "3000:80"
    volumes:
      - ./plugin/:/var/www/html/wp-content/plugins/react-quiz/
  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=my-wpdb
